server:
  port: 7070

spring:
  application:
    name: quickbite

  datasource:
    url: jdbc:postgresql://localhost:5432/quickbite
    username: postgres
    password: possql312
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: quickbite-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
